
var nodes= [{"name":"strong uk"},
{"name":"flavor germany"},
{"name":"cool germany"},
{"name":"fresh refreshing germany"},
{"name":"thin dry germany"},
{"name":"thin round germany"},
{"name":"fruity sweet light germany"},
{"name":"sweet sour china"},
{"name":"fruity germany"},
{"name":"round germany"},
{"name":"thin germany"},
{"name":"flavor light germany"},
{"name":"thin plain germany"},
{"name":"fruity uk"},
{"name":"flavor china"},
{"name":"sweet us"},
{"name":"light china"},
{"name":"thin tar germany"},
{"name":"sour germany"},
{"name":"thin china"},
{"name":"light germany"},
{"name":"flavor spain"},
{"name":""},
{"name":"sour china"},
{"name":"sweet spain"},
{"name":"chocolate uk"},
{"name":"soft china"},
{"name":"hot germany"},
{"name":"sweet germany"},
{"name":"sweet uk"},
{"name":"dry germany"},
{"name":"strong china"},
{"name":"full-bodied germany"},
{"name":"light uk"},
{"name":"strong germany"},
{"name":"thin aged germany"},
{"name":"mild germany"},
{"name":"berry germany"},
{"name":"fresh refreshing china"},
{"name":"round uk"},
{"name":"sage uk"},
{"name":"tar italy"},
{"name":"smooth uk"},
{"name":"dry full-bodied germany"},
{"name":"thin italy"},
{"name":"heavy germany"},
{"name":"rose uk"},
{"name":"fruity dry germany"},
{"name":"fruity light germany"},
{"name":"plain china"},
{"name":"rich china"},
{"name":"aged germany"},
{"name":"thin uk"},
{"name":"sage china"},
{"name":"light france"},
{"name":"thin tar tart germany"},
{"name":"thin sweet germany"},
{"name":"burn germany"},
{"name":"aged uk"},
{"name":"fruity sweet germany"},
{"name":"sweet rose germany"},
{"name":"heavy china"},
{"name":"dry china"},
{"name":"sweet light germany"},
{"name":"thin spain"},
{"name":"astringent china"},
{"name":"rose germany"},
{"name":"sweet china"},
{"name":"tar germany"},
{"name":"fresh refreshing uk"},
{"name":"hot uk"},
{"name":"flavor us"},
{"name":"thin sweet spain"},
{"name":"fruity china"},
{"name":"fruity soft germany"},
{"name":"sweet dry germany"},
{"name":"plain uk"},
{"name":"rich uk"},
{"name":"thin rose germany"},
{"name":"thin fruity sweet germany"},
{"name":"soft spain"},
{"name":"fresh germany"},
{"name":"tar uk"},
{"name":"aged china"},
]
var colors= []
var links = [{ source: nodes[1], target: nodes[80]},
{ source: nodes[3], target: nodes[69]},
{ source: nodes[3], target: nodes[18]},
{ source: nodes[3], target: nodes[45]},
{ source: nodes[3], target: nodes[37]},
{ source: nodes[4], target: nodes[0]},
{ source: nodes[47], target: nodes[81]},
{ source: nodes[7], target: nodes[79]},
{ source: nodes[9], target: nodes[21]},
{ source: nodes[10], target: nodes[64]},
{ source: nodes[10], target: nodes[19]},
{ source: nodes[10], target: nodes[44]},
{ source: nodes[10], target: nodes[52]},
{ source: nodes[10], target: nodes[12]},
{ source: nodes[10], target: nodes[51]},
{ source: nodes[10], target: nodes[68]},
{ source: nodes[14], target: nodes[71]},
{ source: nodes[13], target: nodes[81]},
{ source: nodes[13], target: nodes[18]},
{ source: nodes[16], target: nodes[43]},
{ source: nodes[16], target: nodes[62]},
{ source: nodes[16], target: nodes[23]},
{ source: nodes[16], target: nodes[6]},
{ source: nodes[16], target: nodes[73]},
{ source: nodes[75], target: nodes[24]},
{ source: nodes[75], target: nodes[59]},
{ source: nodes[75], target: nodes[29]},
{ source: nodes[75], target: nodes[30]},
{ source: nodes[18], target: nodes[3]},
{ source: nodes[19], target: nodes[44]},
{ source: nodes[19], target: nodes[64]},
{ source: nodes[19], target: nodes[52]},
{ source: nodes[19], target: nodes[10]},
{ source: nodes[19], target: nodes[9]},
{ source: nodes[21], target: nodes[80]},
{ source: nodes[21], target: nodes[1]},
{ source: nodes[0], target: nodes[77]},
{ source: nodes[0], target: nodes[69]},
{ source: nodes[22], target: nodes[46]},
{ source: nodes[22], target: nodes[42]},
{ source: nodes[23], target: nodes[7]},
{ source: nodes[23], target: nodes[60]},
{ source: nodes[24], target: nodes[75]},
{ source: nodes[24], target: nodes[15]},
{ source: nodes[24], target: nodes[29]},
{ source: nodes[24], target: nodes[56]},
{ source: nodes[26], target: nodes[61]},
{ source: nodes[28], target: nodes[8]},
{ source: nodes[28], target: nodes[63]},
{ source: nodes[28], target: nodes[30]},
{ source: nodes[28], target: nodes[4]},
{ source: nodes[28], target: nodes[59]},
{ source: nodes[30], target: nodes[59]},
{ source: nodes[30], target: nodes[47]},
{ source: nodes[30], target: nodes[75]},
{ source: nodes[30], target: nodes[28]},
{ source: nodes[30], target: nodes[24]},
{ source: nodes[31], target: nodes[61]},
{ source: nodes[20], target: nodes[74]},
{ source: nodes[20], target: nodes[11]},
{ source: nodes[20], target: nodes[48]},
{ source: nodes[33], target: nodes[21]},
{ source: nodes[33], target: nodes[27]},
{ source: nodes[33], target: nodes[58]},
{ source: nodes[33], target: nodes[37]},
{ source: nodes[35], target: nodes[12]},
{ source: nodes[35], target: nodes[41]},
{ source: nodes[35], target: nodes[51]},
{ source: nodes[35], target: nodes[68]},
{ source: nodes[36], target: nodes[80]},
{ source: nodes[36], target: nodes[77]},
{ source: nodes[37], target: nodes[45]},
{ source: nodes[37], target: nodes[3]},
{ source: nodes[37], target: nodes[1]},
{ source: nodes[40], target: nodes[76]},
{ source: nodes[40], target: nodes[70]},
{ source: nodes[41], target: nodes[35]},
{ source: nodes[41], target: nodes[12]},
{ source: nodes[42], target: nodes[21]},
{ source: nodes[42], target: nodes[45]},
{ source: nodes[42], target: nodes[36]},
{ source: nodes[42], target: nodes[3]},
{ source: nodes[43], target: nodes[79]},
{ source: nodes[44], target: nodes[64]},
{ source: nodes[44], target: nodes[52]},
{ source: nodes[44], target: nodes[68]},
{ source: nodes[44], target: nodes[19]},
{ source: nodes[44], target: nodes[82]},
{ source: nodes[44], target: nodes[41]},
{ source: nodes[57], target: nodes[72]},
{ source: nodes[25], target: nodes[0]},
{ source: nodes[8], target: nodes[13]},
{ source: nodes[8], target: nodes[63]},
{ source: nodes[8], target: nodes[81]},
{ source: nodes[8], target: nodes[18]},
{ source: nodes[8], target: nodes[3]},
{ source: nodes[46], target: nodes[58]},
{ source: nodes[46], target: nodes[66]},
{ source: nodes[46], target: nodes[51]},
{ source: nodes[46], target: nodes[33]},
{ source: nodes[46], target: nodes[42]},
{ source: nodes[46], target: nodes[2]},
{ source: nodes[12], target: nodes[35]},
{ source: nodes[12], target: nodes[41]},
{ source: nodes[48], target: nodes[81]},
{ source: nodes[11], target: nodes[5]},
{ source: nodes[51], target: nodes[58]},
{ source: nodes[51], target: nodes[27]},
{ source: nodes[51], target: nodes[35]},
{ source: nodes[51], target: nodes[68]},
{ source: nodes[51], target: nodes[33]},
{ source: nodes[51], target: nodes[64]},
{ source: nodes[51], target: nodes[2]},
{ source: nodes[51], target: nodes[12]},
{ source: nodes[52], target: nodes[44]},
{ source: nodes[52], target: nodes[64]},
{ source: nodes[52], target: nodes[19]},
{ source: nodes[52], target: nodes[82]},
{ source: nodes[52], target: nodes[53]},
{ source: nodes[52], target: nodes[68]},
{ source: nodes[69], target: nodes[77]},
{ source: nodes[56], target: nodes[15]},
{ source: nodes[77], target: nodes[0]},
{ source: nodes[77], target: nodes[69]},
{ source: nodes[77], target: nodes[36]},
{ source: nodes[58], target: nodes[51]},
{ source: nodes[58], target: nodes[46]},
{ source: nodes[58], target: nodes[33]},
{ source: nodes[58], target: nodes[27]},
{ source: nodes[58], target: nodes[2]},
{ source: nodes[58], target: nodes[35]},
{ source: nodes[58], target: nodes[66]},
{ source: nodes[59], target: nodes[30]},
{ source: nodes[59], target: nodes[75]},
{ source: nodes[59], target: nodes[47]},
{ source: nodes[59], target: nodes[24]},
{ source: nodes[54], target: nodes[39]},
{ source: nodes[60], target: nodes[79]},
{ source: nodes[61], target: nodes[26]},
{ source: nodes[63], target: nodes[4]},
{ source: nodes[63], target: nodes[18]},
{ source: nodes[63], target: nodes[81]},
{ source: nodes[64], target: nodes[44]},
{ source: nodes[64], target: nodes[68]},
{ source: nodes[64], target: nodes[52]},
{ source: nodes[64], target: nodes[82]},
{ source: nodes[64], target: nodes[19]},
{ source: nodes[65], target: nodes[26]},
{ source: nodes[65], target: nodes[61]},
{ source: nodes[65], target: nodes[31]},
{ source: nodes[65], target: nodes[50]},
{ source: nodes[66], target: nodes[46]},
{ source: nodes[66], target: nodes[58]},
{ source: nodes[66], target: nodes[35]},
{ source: nodes[66], target: nodes[27]},
{ source: nodes[66], target: nodes[2]},
{ source: nodes[67], target: nodes[23]},
{ source: nodes[67], target: nodes[15]},
{ source: nodes[68], target: nodes[64]},
{ source: nodes[68], target: nodes[44]},
{ source: nodes[68], target: nodes[41]},
{ source: nodes[68], target: nodes[35]},
{ source: nodes[68], target: nodes[51]},
{ source: nodes[68], target: nodes[82]},
{ source: nodes[45], target: nodes[37]},
{ source: nodes[45], target: nodes[36]},
{ source: nodes[45], target: nodes[3]},
{ source: nodes[45], target: nodes[77]},
{ source: nodes[70], target: nodes[78]},
{ source: nodes[70], target: nodes[76]},
{ source: nodes[49], target: nodes[83]},
{ source: nodes[32], target: nodes[39]},
{ source: nodes[32], target: nodes[5]},
{ source: nodes[76], target: nodes[78]},
{ source: nodes[76], target: nodes[70]},
{ source: nodes[78], target: nodes[76]},
{ source: nodes[78], target: nodes[70]},
{ source: nodes[80], target: nodes[36]},
{ source: nodes[80], target: nodes[77]},
{ source: nodes[80], target: nodes[1]},
{ source: nodes[55], target: nodes[38]},
{ source: nodes[34], target: nodes[37]},
{ source: nodes[34], target: nodes[45]},
{ source: nodes[81], target: nodes[13]},
{ source: nodes[81], target: nodes[48]},
{ source: nodes[17], target: nodes[82]},
{ source: nodes[17], target: nodes[83]},
{ source: nodes[83], target: nodes[49]},
]
